### ISSUE TITLE
Incorrect homepage link on RubyGems.org

### ISSUE THREAD

**Issue by jnimety** [usnationalarchives/federal_register#8]
https://rubygems.org/gems/federal_register links to http://github.com/criticaljuncture/federal_register for the homepage.

**Comment by nickborromeo** [comment]
@peregrinator @andrewcarpenter I was looking into this project to see if I could help, and noticed that this issue does not seem to valid anymore. I think this can be closed 😄

**Comment by peregrinator** [comment]
Thanks!
